@startuml

class Categoria {
    - nombre: String
    - id: Long
}

class Coleccion {
    - titulo: String
    - descripcion: String
    - fuente: Fuente
    - criterios: Set<Criterio>
    - hechosDeLaColeccion: List<Hecho>
    + filtrarHechos(): void
    + agregarHechos(List<Hecho> hechos): void
    + cumpleLosCriterios(Hecho hecho): boolean
    + noFueEliminado(Hecho hecho): boolean
    + agregarCriterios(Criterio ... nuevosCriterios): void
}

class ContenidoMultimedia {
    - path: String
    - idContenidoMultimedia: Long
}

class Administrador {
    - nombre: String
    - apellido: String
}

class Contribuyente {
    - nombre: String
    - apellido: String
    - fechaDeNacimiento: LocalDate
    + getEdad: Integer
}

class Etiqueta {
    - nombre: String
    - id: Long
}

class Hecho {
    - id: Long
    - titulo: String
    - descripcion: String
    - categoria: Categoria
    - ubicacion: Ubicacion
    - fechaAcontecimiento: LocalDate
    - fechaCarga: LocalDate
    - origen: Origen
    - fueEliminado: boolean
    - etiquetas: Set<Etiqueta>
    - idContribuyente: Long
    - contenidosMultimedia: List<ContenidoMultimedia>
    - estadoPrevio: HechoEstadoPrevio

    + agregarEtiqueta(etiqueta: Etiqueta): void
    + actualizarHecho(titulo: String, descripcion: String, categoria: Categoria, ubicacion: Ubicacion, fechaAcontecimiento: LocalDate): void
    + getPathsMultimedia(List<ContenidoMultimedia> contenidos): List<String>
}

class HechoEstadoPrevio {
    - descripcion: String
    - categoria: Categoria
    - ubicacion: Ubicacion
    - fechaAcontecimiento: LocalDate
    - contenidosMultimedia: List<ContenidoMultimedia>
}

class Solicitud {
    - id: Long
    - tipoSolicitud: TipoSolicitud
    - hecho: Hecho
    - estado: EstadoSolicitud
    - fechaSolicitud: LocalDate
    - fechaAtencion: LocalDate
    - comentario: String
    - idAdministradorQueAtendio: Long
    + cambiarEstado(nuevoEstado: EstadoSolicitud): void
}

interface Criterio {
    +cumpleCriterio(hecho: Hecho): boolean
}

class Ubicacion {
    - latitud: Double
    - longitud: Double
}

class CriterioTitulo implements Criterio{
    -titulo: String

    +cumpleCriterio(hecho: Hecho): boolean
}

class CriterioDescripcion implements Criterio{
    -descripcion: String

    +cumpleCriterio(hecho: Hecho): boolean
}

class CriterioCategoria implements Criterio{
    -categoria: String

    +cumpleCriterio(hecho: Hecho): boolean
}

class CriterioLugar implements Criterio {
    -ubicacion: Ubicacion
    -rangoMaximo: Integer

    +cumpleCriterio(hecho: Hecho): boolean
}

class CriterioFechaAcontecimiento implements Criterio{
    -desde: LocalDate
    -hasta: LocalDate

    +cumpleCriterio(hecho: Hecho): boolean
}

class CriterioFechaCarga implements Criterio{
    -desde: LocalDate
    -hasta: LocalDate

    +cumpleCriterio(hecho: Hecho): boolean
}

class CriterioOrigen implements Criterio{
    -origen: Origen

    +cumpleCriterio(hecho: Hecho): boolean
}

enum EstadoSolicitud {
    PENDIENTE
    RECHAZADA
    ACEPTADA
}

enum Origen {
  CARGA_MANUAL
  PROVENIENTE_DE_DATASET
  PROVISTO_POR_CONTRIBUYENTE
}

enum TipoSolicitud {
  CREACION
  EDICION
}

Coleccion --> "*" Criterio
Coleccion --> "*" Hecho
Coleccion --> Fuente
Hecho --> Origen
Hecho --> "*" Etiqueta
Solicitud --> Hecho
Solicitud --> EstadoSolicitud
Solicitud --> Administrador
Solicitud --> "*" Contribuyente
Hecho --> Ubicacion
Hecho --> Categoria
Hecho --> "*" ContenidoMultimedia
Hecho --> HechoEstadoPrevio
CriterioLugar --> Ubicacion
CriterioCategoria --> Categoria
Solicitud --> TipoSolicitud

@enduml